All debug messages present in logfile
cinek810/ansible-deployer pull request #129
Opened 2022-04-22 12:35 UTC by LegenJCdary

2022-05-17 12:16 UTC, cinek810 requested changes

2022-05-17 12:16 UTC, cinek810 commented on source/main.py
> +        logger.logger.handlers[0].setTarget(logger.logger.handlers[2])
what's handlers[2]? Need at least comment on that to avoid issues from other changes - is that vulnerable to loggers definition order?

2022-05-20 07:55 UTC, LegenJCdary commented on source/main.py
>      configuration = Config(logger.logger, options["conf_dir"])
I reduced number of statements to pass pylint test.

2022-06-02 08:12 UTC, cinek810 approved these changes
Just remove the line instead of commenting it out

2022-06-21 12:56 UTC, merged